project:
  type: book
  preview:
    port: 17487

book:
  title: "Better Budget Goals"
  page-navigation: true
  chapters:
    - index.qmd
    - introduction.qmd
    - basics.qmd
    - details.qmd
    - full.qmd


format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
  pdf:
    toc: true