
# Proposed Algorithm Basics {#sec-basics}

```{python}
#| label: setup
#| include: false

import pandas as pd
from IPython.display import Markdown
from tabulate import tabulate
import matplotlib.pyplot as plt
import numpy as np

from betterbudgetgoals.month import YearMonth
from betterbudgetgoals.algo import GradualGoal, contribution_amounts

```

To understand the basics of the proposed algorithm we'll start with a simplified case: multiple `by`-type templates in a single category, no repeating, no other templates, no priorities, and no `spend from` clauses. Then we'll build back in these other details in the next section. The approach for this simplified case is given in [Algorithm @alg-basic].

:::{#alg-basic}

### Basic Algorithm 

*Multiple non-repeating `by`-type templates in a single category.*

**Input:**

1. `current_month`, the current month
2. `current_balance`, the category balance carried over from the previous month
3. `templates = [(month, amount),...]`, a list of templates.

**Output:** The amount to budget in the current month.

**Steps:**

1. Sort `templates` increasing by month.
2. Set `total_target = -current_balance`.
3. Set `max_budget = -inf`.
4. For each template in `templates`:
    1. Set `total_target += amount`
    2. Set `budget = total_target / (month - current_month + 1)`.
    3. If `budget > max_budget`: set `max_budget = budget`
5. Return `max_budget`.

:::

::: {.callout-note}
[Algorithm @alg-basic] can be more simply described in these three steps:

1. Convert each template into a cumulative target. (Calculate the total amount of additional money required to meet itself and all previous templates.)
2. For each cumulative target, calculate the monthly contribution from now required to meet the target.
3. Return the maximum required monthly contribution.

:::

Let's apply this to @exm-multiple-by.

... blah ...

We can visualize this situation as a series of cumulative milestones (@fig-cumulative-milestones). To meet all of the goals, we need to make a series of budget contributions which cumulatively stay above all the milestones on this graph.

```{python}
#| label: fig-cumulative-milestones
#| echo: false
#| fig-cap: The basic example shown as a series of cumulative milestones. We have $100 initially, and need to have budgeted $300 total by 2026-07, $700 total by 2026-08, and $800 total by 2026-10, in order to meet all three goals.

startmonth = YearMonth(2026,4)
startbalance = 100

df = pd.DataFrame({
    "Month":[startmonth + i for i in range(7)],
    "Templates":[np.nan, np.nan, np.nan, 300, 400, np.nan, 100]
},
index=range(1,8))
df["Targets"] = np.nancumsum(df["Templates"])
df.loc[np.isnan(df["Templates"]), "Targets"] = np.nan

with plt.style.context("ggplot"):
    plt.scatter(df.index, df["Targets"], c="red", marker="D", label="Cumulative Targets")
    plt.scatter([0], [startbalance], c="blue", label="Starting Balance")
    ticks = [0] + list(df.index)
    labels = [f"Start\n(End of {startmonth - 1})"] + list(df["Month"])
    plt.xticks(ticks = ticks, labels = labels, rotation=30, ha="right")
    plt.ylim((0,np.nanmax(df["Targets"])*1.1))
    plt.legend(loc="upper left")
plt.show()

```

